/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz.information.system;

/**
 *
 * @author Sanele
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }
    //A declaration of a public static string to identify users
    public static String strUserIdentifier; 
    
    /*A method that grants system users
    * access rights and priveledges that
    * will be suitable for them to work
    * in the system.
    */
    public void mXYZInformationSystemUserAccessControl()
    {
        switch(strUserIdentifier)
        {
            case "student":
                mnuFile.setEnabled(true);
                mnuRegistration.setVisible(false);
                mnuBursarOptions.setVisible(false);
                mnuClassTeacherOptions.setVisible(false);
                mnuStudentOptions.setEnabled(true);
                break;
            case "teacher":
                mnuFile.setEnabled(true);
                mnuRegistration.setVisible(false);
                mnuBursarOptions.setVisible(false);
                mnuClassTeacherOptions.setEnabled(true);
                mnuStudentOptions.setVisible(false);
                break;
            case "registra":
                mnuFile.setEnabled(true);
                mnuItemCreateRegistrarAccount.setEnabled(true);
                mnuItemRegisterTeachers.setEnabled(true);
                if(frmLogin.strUserID == null){
                    mnuItemRegisterStudents.setEnabled(false);
                }
                mnuBursarOptions.setVisible(false);
                mnuClassTeacherOptions.setVisible(false);
                mnuStudentOptions.setVisible(false);
                break;
            case "bursar":
                mnuFile.setEnabled(true);
                mnuRegistration.setVisible(false);
                mnuBursarOptions.setEnabled(true);
                mnuClassTeacherOptions.setVisible(false);
                mnuStudentOptions.setVisible(false);
                break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsktpMain = new javax.swing.JDesktopPane();
        mbMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItemLogout = new javax.swing.JMenuItem();
        mnuItemExit = new javax.swing.JMenuItem();
        mnuRegistration = new javax.swing.JMenu();
        mnuItemCreateRegistrarAccount = new javax.swing.JMenuItem();
        mnuItemRegisterTeachers = new javax.swing.JMenuItem();
        mnuItemRegisterStudents = new javax.swing.JMenuItem();
        mnuItemRegisterBursar = new javax.swing.JMenuItem();
        mnuBursarOptions = new javax.swing.JMenu();
        mnuItemStudentsAndFees = new javax.swing.JMenuItem();
        mnuItemAccountPayment = new javax.swing.JMenuItem();
        mnuClassTeacherOptions = new javax.swing.JMenu();
        mnuItemViewStudentInTeacherClass = new javax.swing.JMenuItem();
        mnuStudentOptions = new javax.swing.JMenu();
        mnuItemManageStudentDetails = new javax.swing.JMenuItem();
        mnuItemViewStudentInformationAndFinances = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsktpMain.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout dsktpMainLayout = new javax.swing.GroupLayout(dsktpMain);
        dsktpMain.setLayout(dsktpMainLayout);
        dsktpMainLayout.setHorizontalGroup(
            dsktpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1196, Short.MAX_VALUE)
        );
        dsktpMainLayout.setVerticalGroup(
            dsktpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        mnuItemLogout.setText("Logout");
        mnuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemLogout);

        mnuItemExit.setText("Exit");
        mnuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemExit);

        mbMenu.add(mnuFile);

        mnuRegistration.setText("Registration");

        mnuItemCreateRegistrarAccount.setText("Add Registrar Account");
        mnuItemCreateRegistrarAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCreateRegistrarAccountActionPerformed(evt);
            }
        });
        mnuRegistration.add(mnuItemCreateRegistrarAccount);

        mnuItemRegisterTeachers.setText("Register Teachers");
        mnuItemRegisterTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegisterTeachersActionPerformed(evt);
            }
        });
        mnuRegistration.add(mnuItemRegisterTeachers);

        mnuItemRegisterStudents.setText("Register Students");
        mnuItemRegisterStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegisterStudentsActionPerformed(evt);
            }
        });
        mnuRegistration.add(mnuItemRegisterStudents);

        mnuItemRegisterBursar.setText("Register Bursar");
        mnuItemRegisterBursar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegisterBursarActionPerformed(evt);
            }
        });
        mnuRegistration.add(mnuItemRegisterBursar);

        mbMenu.add(mnuRegistration);

        mnuBursarOptions.setText("Bursar Options");

        mnuItemStudentsAndFees.setText("Students and Their Fees");
        mnuItemStudentsAndFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemStudentsAndFeesActionPerformed(evt);
            }
        });
        mnuBursarOptions.add(mnuItemStudentsAndFees);

        mnuItemAccountPayment.setText("Student Account Payment");
        mnuItemAccountPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAccountPaymentActionPerformed(evt);
            }
        });
        mnuBursarOptions.add(mnuItemAccountPayment);

        mbMenu.add(mnuBursarOptions);

        mnuClassTeacherOptions.setText("Class Teacher Options");

        mnuItemViewStudentInTeacherClass.setText("View Students Enrolled In Your Class");
        mnuItemViewStudentInTeacherClass.setActionCommand("Students Enrolled In Your Class");
        mnuItemViewStudentInTeacherClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViewStudentInTeacherClassActionPerformed(evt);
            }
        });
        mnuClassTeacherOptions.add(mnuItemViewStudentInTeacherClass);

        mbMenu.add(mnuClassTeacherOptions);

        mnuStudentOptions.setText("Student Options");

        mnuItemManageStudentDetails.setText("Manage Your Student Details");
        mnuItemManageStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemManageStudentDetailsActionPerformed(evt);
            }
        });
        mnuStudentOptions.add(mnuItemManageStudentDetails);

        mnuItemViewStudentInformationAndFinances.setText("View Your Student Information And Finances");
        mnuItemViewStudentInformationAndFinances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViewStudentInformationAndFinancesActionPerformed(evt);
            }
        });
        mnuStudentOptions.add(mnuItemViewStudentInformationAndFinances);

        mbMenu.add(mnuStudentOptions);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dsktpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogoutActionPerformed
        frmLogin frmlogin = new frmLogin();
        frmlogin.setExtendedState(MAXIMIZED_BOTH);
        frmlogin.setTitle("XYZ Information System Login Screen");
        frmlogin.show();
        this.hide();
    }//GEN-LAST:event_mnuItemLogoutActionPerformed

    private void mnuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItemExitActionPerformed

    private void mnuItemCreateRegistrarAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCreateRegistrarAccountActionPerformed
        frmTeacherRegistrations frmRegistraRegistration = new frmTeacherRegistrations("registrar");
        frmRegistraRegistration.strRegisterWhichUser = "registrar";
        frmRegistraRegistration.setTitle("Register Registrar Account");
        dsktpMain.add(frmRegistraRegistration);
        frmRegistraRegistration.setLocation(400, 100);
        frmRegistraRegistration.setClosable(true);
        frmRegistraRegistration.setVisible(true);
    }//GEN-LAST:event_mnuItemCreateRegistrarAccountActionPerformed

    private void mnuItemRegisterTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegisterTeachersActionPerformed
        frmTeacherRegistrations frmTeacherRegistration = new frmTeacherRegistrations("teacher");
        frmTeacherRegistration.strRegisterWhichUser = "teacher";
        frmTeacherRegistration.setTitle("Register Teacher Account");
        dsktpMain.add(frmTeacherRegistration);
        frmTeacherRegistration.setLocation(400, 100);
        frmTeacherRegistration.setClosable(true);
        frmTeacherRegistration.setVisible(true);
    }//GEN-LAST:event_mnuItemRegisterTeachersActionPerformed

    private void mnuItemRegisterStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegisterStudentsActionPerformed
        frmStudentRegistrations frmStudRegistration = new frmStudentRegistrations();
        frmStudRegistration.setTitle("Student Registration");
        dsktpMain.add(frmStudRegistration);
        frmStudRegistration.setLocation(400, 50);
        frmStudRegistration.setClosable(true);
        frmStudRegistration.setVisible(true);
    }//GEN-LAST:event_mnuItemRegisterStudentsActionPerformed

    private void mnuItemManageStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemManageStudentDetailsActionPerformed
        frmStudentRegistrations frmStudAccountManagement = new frmStudentRegistrations();
        frmStudAccountManagement.setTitle("Student Account Management");
        frmStudAccountManagement.mSetAccountManagementGUI();
        dsktpMain.add(frmStudAccountManagement);
        frmStudAccountManagement.setLocation(400, 70);
        frmStudAccountManagement.setClosable(true);
        frmStudAccountManagement.setVisible(true);
    }//GEN-LAST:event_mnuItemManageStudentDetailsActionPerformed

    private void mnuItemStudentsAndFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemStudentsAndFeesActionPerformed
        frmStudentsEnrolled frmStudEnrolled = new frmStudentsEnrolled();
        frmStudEnrolled.setTitle("Students Enrolled at XYZ Secondary");
        frmStudEnrolled.setExtendedState(MAXIMIZED_BOTH);
        frmStudEnrolled.setVisible(true);
        this.hide();
    }//GEN-LAST:event_mnuItemStudentsAndFeesActionPerformed

    private void mnuItemAccountPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAccountPaymentActionPerformed
        frmStudentAccountPayment frmStudAccountPayment = new frmStudentAccountPayment();
        frmStudAccountPayment.setTitle("Student Accounts Payment");
        dsktpMain.add(frmStudAccountPayment);
        frmStudAccountPayment.setLocation(400, 100);
        frmStudAccountPayment.setClosable(true);
        frmStudAccountPayment.setVisible(true);
    }//GEN-LAST:event_mnuItemAccountPaymentActionPerformed

    private void mnuItemViewStudentInformationAndFinancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViewStudentInformationAndFinancesActionPerformed
        frmStudentAccountPayment frmViewStudentDetailsAndFinances = new frmStudentAccountPayment();
        frmViewStudentDetailsAndFinances.setTitle("Your Details and Financial Account Standings");
        frmViewStudentDetailsAndFinances.mViewStudentDetailsAndFees();
        dsktpMain.add(frmViewStudentDetailsAndFinances);
        frmViewStudentDetailsAndFinances.setLocation(400, 100);
        frmViewStudentDetailsAndFinances.setClosable(true);
        frmViewStudentDetailsAndFinances.setVisible(true);
    }//GEN-LAST:event_mnuItemViewStudentInformationAndFinancesActionPerformed

    private void mnuItemViewStudentInTeacherClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViewStudentInTeacherClassActionPerformed
        frmTeacherRegistrations frmViewStudentsEnrolledInTeacherClass = new frmTeacherRegistrations("");
        frmViewStudentsEnrolledInTeacherClass.setTitle("Students enrolled in your class");
        frmViewStudentsEnrolledInTeacherClass.mViewStudentsDetails("");
        dsktpMain.add(frmViewStudentsEnrolledInTeacherClass);
        frmViewStudentsEnrolledInTeacherClass.setLocation(400, 100);
        frmViewStudentsEnrolledInTeacherClass.setClosable(true);
        frmViewStudentsEnrolledInTeacherClass.setVisible(true);
    }//GEN-LAST:event_mnuItemViewStudentInTeacherClassActionPerformed

    private void mnuItemRegisterBursarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegisterBursarActionPerformed
        frmTeacherRegistrations frmRegistraRegistration = new frmTeacherRegistrations("bursar");
        frmRegistraRegistration.strRegisterWhichUser = "bursar";
        frmRegistraRegistration.setTitle("Register Bursar Account");
        dsktpMain.add(frmRegistraRegistration);
        frmRegistraRegistration.setLocation(400, 100);
        frmRegistraRegistration.setClosable(true);
        frmRegistraRegistration.setVisible(true);
    }//GEN-LAST:event_mnuItemRegisterBursarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dsktpMain;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenu mnuBursarOptions;
    private javax.swing.JMenu mnuClassTeacherOptions;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuItemAccountPayment;
    private javax.swing.JMenuItem mnuItemCreateRegistrarAccount;
    private javax.swing.JMenuItem mnuItemExit;
    private javax.swing.JMenuItem mnuItemLogout;
    private javax.swing.JMenuItem mnuItemManageStudentDetails;
    private javax.swing.JMenuItem mnuItemRegisterBursar;
    private javax.swing.JMenuItem mnuItemRegisterStudents;
    private javax.swing.JMenuItem mnuItemRegisterTeachers;
    private javax.swing.JMenuItem mnuItemStudentsAndFees;
    private javax.swing.JMenuItem mnuItemViewStudentInTeacherClass;
    private javax.swing.JMenuItem mnuItemViewStudentInformationAndFinances;
    private javax.swing.JMenu mnuRegistration;
    private javax.swing.JMenu mnuStudentOptions;
    // End of variables declaration//GEN-END:variables
}
