/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz.information.system;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
    * @author Sanele
 */
public class frmStudentsEnrolled extends javax.swing.JFrame {

    /**
     * Creates new form frmStudentsEnrolled
     */
    public frmStudentsEnrolled() {
        initComponents();
        mPopulateStudentsNamesComboBox(mFetchStudentsNamesQuery());
    }
    
    //Instantiations of object of class clsConnectToDatabase and of class clsQueryingMethods
    clsConnectToDatabase clsConnect = new clsConnectToDatabase();
    clsSQLMethods clsQueryingMethods = new clsSQLMethods();
       
    //A method that returns as string a query that 
    //fetches student names from the database
    private String mFetchStudentsNamesQuery()
    {
        return "SELECT NAME FROM tblStudents";
    }
    
    //A method that connects to the database and load data to a 
    //combo box as values.
    private void mPopulateStudentsNamesComboBox(String strQuery)
    {
        try
        {
            try (Statement stStatement = clsConnect.mConnectToXYZInformationSystem().prepareStatement(strQuery)) {
                stStatement.execute(strQuery);
                try (ResultSet rs = stStatement.getResultSet()) {
                    while(rs.next())
                    {
                        cboEnrolledStudents.addItem(rs.getString(1));
                    }
                    stStatement.close();
                    rs.close();
                }
            }
        }
        catch(SQLException eX)
        {
            JOptionPane.showMessageDialog(null,"A technical error has been encountered\n"+eX);
        }
    }
    
    //A method that returns as integer an ID of a student
    private int mStudentID()
    {
        return clsQueryingMethods.mGetNumericColumn("SELECT ID FROM tblStudents WHERE Name='"+
                        cboEnrolledStudents.getSelectedItem().toString()+"'");
    }
    
    //A method that returns as double an amount
    //of fees paid by a student.
    private double mAmountPaid()
    {
        return (double)clsQueryingMethods.mGetNumericColumn("SELECT SUM(Amount) FROM tblAccounts WHERE Student='"
                +mStudentID()+"'");
    }
    
    //A method that returns as double a class
    //amount that a student is enrolled in
    private double mClassYearlyAmount()
    {
        return (double)clsQueryingMethods.mGetNumericColumn("SELECT ClassAmount FROM tblClass WHERE ID='"+
                clsQueryingMethods.mGetNumericColumn("SELECT ClassEnrolledIn FROM tblStudents WHERE ID ='"+
                    mStudentID()+"'")+"'");
    }
    
    //A method that returns as string a query that views student
    //details and financial standings.
    private String mViewStudentsDetailsAndFinancesQuery()
    {
        return "SELECT Name, DOB, Gender, Address, ClassEnrolledIn, "
                +mClassYearlyAmount()+" AS ClassYearlyAmount, "
                +mAmountPaid()+" AS AmountPaid, "+(mClassYearlyAmount()
                - mAmountPaid())+" AS FeesToBePaid FROM tblStudents WHERE ID ='"
                +mStudentID()+"'";
    }
    
    private String mViewFullFinancialStatementQuery()
    {
        return "SELECT ID AS PaymentID, (SELECT Name FROM tblStudents WHERE ID = "+mStudentID()+") AS Student, PaymentDate,"
                + " Amount, FeesToBePaid FROM tblAccounts WHERE Student ='"+mStudentID()+"'";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsktpStudentsEnrolled = new javax.swing.JDesktopPane();
        lblHeading = new javax.swing.JLabel();
        lblSelectStudent = new javax.swing.JLabel();
        cboEnrolledStudents = new javax.swing.JComboBox<>();
        btnViewStudentDetailsAndFinances = new javax.swing.JButton();
        btnReturnToPreviousPage = new javax.swing.JButton();
        btnStudentFullStmt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsktpStudentsEnrolled.setBackground(new java.awt.Color(255, 204, 153));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setText("Enrolled Students");

        lblSelectStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSelectStudent.setText("Select Student");

        btnViewStudentDetailsAndFinances.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewStudentDetailsAndFinances.setText("View Student Details And Finances");
        btnViewStudentDetailsAndFinances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentDetailsAndFinancesActionPerformed(evt);
            }
        });

        btnReturnToPreviousPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReturnToPreviousPage.setText("Return to Previous Page");
        btnReturnToPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToPreviousPageActionPerformed(evt);
            }
        });

        btnStudentFullStmt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStudentFullStmt.setText("Student Full Finance Stmt");
        btnStudentFullStmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentFullStmtActionPerformed(evt);
            }
        });

        dsktpStudentsEnrolled.setLayer(lblHeading, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpStudentsEnrolled.setLayer(lblSelectStudent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpStudentsEnrolled.setLayer(cboEnrolledStudents, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpStudentsEnrolled.setLayer(btnViewStudentDetailsAndFinances, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpStudentsEnrolled.setLayer(btnReturnToPreviousPage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpStudentsEnrolled.setLayer(btnStudentFullStmt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dsktpStudentsEnrolledLayout = new javax.swing.GroupLayout(dsktpStudentsEnrolled);
        dsktpStudentsEnrolled.setLayout(dsktpStudentsEnrolledLayout);
        dsktpStudentsEnrolledLayout.setHorizontalGroup(
            dsktpStudentsEnrolledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsktpStudentsEnrolledLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(dsktpStudentsEnrolledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dsktpStudentsEnrolledLayout.createSequentialGroup()
                        .addComponent(btnViewStudentDetailsAndFinances)
                        .addGap(252, 252, 252)
                        .addComponent(btnStudentFullStmt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReturnToPreviousPage))
                    .addGroup(dsktpStudentsEnrolledLayout.createSequentialGroup()
                        .addComponent(lblSelectStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboEnrolledStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsktpStudentsEnrolledLayout.createSequentialGroup()
                .addContainerGap(638, Short.MAX_VALUE)
                .addComponent(lblHeading)
                .addGap(591, 591, 591))
        );
        dsktpStudentsEnrolledLayout.setVerticalGroup(
            dsktpStudentsEnrolledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsktpStudentsEnrolledLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblHeading)
                .addGap(160, 160, 160)
                .addGroup(dsktpStudentsEnrolledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectStudent)
                    .addComponent(cboEnrolledStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(dsktpStudentsEnrolledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewStudentDetailsAndFinances)
                    .addComponent(btnReturnToPreviousPage)
                    .addComponent(btnStudentFullStmt))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpStudentsEnrolled)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpStudentsEnrolled)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewStudentDetailsAndFinancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentDetailsAndFinancesActionPerformed
        frmTeacherRegistrations frmViewStudentsDetailsAndFinaces = new frmTeacherRegistrations("");
        frmViewStudentsDetailsAndFinaces.setTitle("Students Enrolled at XYZ Secondary");
        frmViewStudentsDetailsAndFinaces.mViewStudentsDetails(mViewStudentsDetailsAndFinancesQuery());
        dsktpStudentsEnrolled.add(frmViewStudentsDetailsAndFinaces);
        frmViewStudentsDetailsAndFinaces.setLocation(400, 100);
        frmViewStudentsDetailsAndFinaces.setClosable(true);
        frmViewStudentsDetailsAndFinaces.setVisible(true);
    }//GEN-LAST:event_btnViewStudentDetailsAndFinancesActionPerformed

    private void btnReturnToPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToPreviousPageActionPerformed
        frmMain frmMn = new frmMain();
        frmMain.strUserIdentifier = "bursar";
        frmMn.mXYZInformationSystemUserAccessControl();
        frmMn.setTitle("XYZ Information System");
        frmMn.setVisible(true);
        this.setVisible(false);
        frmMn.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnReturnToPreviousPageActionPerformed

    private void btnStudentFullStmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentFullStmtActionPerformed
        frmTeacherRegistrations frmViewStudentsFullFinancialStatement = new frmTeacherRegistrations("");
        frmViewStudentsFullFinancialStatement.setTitle("Student Full Financial Statement");
        frmViewStudentsFullFinancialStatement.mViewStudentsDetails(mViewFullFinancialStatementQuery());
        dsktpStudentsEnrolled.add(frmViewStudentsFullFinancialStatement);
        frmViewStudentsFullFinancialStatement.setLocation(400, 100);
        frmViewStudentsFullFinancialStatement.setClosable(true);
        frmViewStudentsFullFinancialStatement.setVisible(true);
    }//GEN-LAST:event_btnStudentFullStmtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStudentsEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStudentsEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStudentsEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStudentsEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStudentsEnrolled().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToPreviousPage;
    private javax.swing.JButton btnStudentFullStmt;
    private javax.swing.JButton btnViewStudentDetailsAndFinances;
    private javax.swing.JComboBox<String> cboEnrolledStudents;
    private javax.swing.JDesktopPane dsktpStudentsEnrolled;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblSelectStudent;
    // End of variables declaration//GEN-END:variables
}
